### ISSUE TITLE
import molgen

### ISSUE THREAD

**Issue by vdfsen** [youliangzhu/pygamd-v1#4]
what is the difference between "import molgen" and "from poetry import molgen" ?
first one is more likely old code from GALAMOST,
in the new pygamd, it shows error when I run "from poetry import molgen"
ImportError: cannot import name 'molgen' from 'poetry' (C:\Users\xxx\pygamd-v1-main\poetry\__init__.py)

How to debug and correct this ?

**Comment by ZhuochenYu** [comment]
> what is the difference between "import molgen" and "from poetry import molgen" ? first one is more likely old code from GALAMOST, in the new pygamd, it shows error when I run "from poetry import molgen" ImportError: cannot import name 'molgen' from 'poetry' (C:\Users\xxx\pygamd-v1-main\poetry__init__.py)
> 
> How to debug and correct this ?

Pygamd only supports importing molgen on linux so far. This is because we only compiled the linux version of molgen as a python library. Later versions will support molgen for windows.

**Comment by SHutdog** [comment]
当我直接试运行examples里的A5B5.molg时（examples/cuda/Case1-DPD/Phase-Seperation-of-Diblock-Copolymer/systems/A5B5）我遇到了一个报错：
Traceback (most recent call last):
  File "/home/yang/桌面/Case1-DPD/Phase-Seperation-of-Diblock-Copolymer/systems/A5B5/A5B5.molg", line 2, in <module>
    from poetry import molgen
ModuleNotFoundError: No module named 'poetry'
当我尝试通过“pip install poetry”指令安装poetry后，上述问题并未解决，环境是官方推荐的的环境，这是为什么呢？

**Comment by whereisLan** [comment]
Today I saw this paper-"Polymer molecular dynamics software PyGAMD and its adaptation to a domestic heterogeneous computing platform". 
There are some description about pygamd,
for example,"Currently, PyGAMD can be installed and used on Linux and Windows platforms, platform requirements: Intel/AMD CPU, NVIDIA GPU or domestic heterogeneous acceleration card, python 3.11 and CUDA Toolkit (>=12.2)."
Does this mean that later versions are already support molgen for windows.
If this hypothesis  is true，why it still shows error when I run "import molgen".
ModuleNotFoundError: No module named 'molgen'
What's more,I saw the molgen is in a file(E:\Python\Lib\site-packages\poetry),named "molgen.so","molgen.pyd",the filename extension-".so" is seem just adjust for Linux systems.
So, whether later versions has supported molgen for windows? If support,what can i do to this error? Thanks!

**Comment by ZhuochenYu** [comment]
1. Download and install Anaconda for windows; Open Anaconda Prompt.
2. Then use 'conda create -n pygamd python=3.11' to build a python env.
3. 'conda activate pygamd' and install cudatoolkit: 'conda install -c 'nvidia/label/cuda-12.2.0' package' 
4. Install pygamd: 'pip install pygamd'

Hope that may help you. 



***@***.***
 
From: whereisLan
Date: 2024-09-06 16:27
To: youliangzhu/pygamd-v1
CC: zcyu; Comment
Subject: Re: [youliangzhu/pygamd-v1] import molgen (Issue #4)
Today I saw this paper-"Polymer molecular dynamics software PyGAMD and its adaptation to a domestic heterogeneous computing platform".
There are some description about pygamd,
for example,"Currently, PyGAMD can be installed and used on Linux and Windows platforms, platform requirements: Intel/AMD CPU, NVIDIA GPU or domestic heterogeneous acceleration card, python 3.11 and CUDA Toolkit (>=12.2)."
Does this mean that later versions are already support molgen for windows.
If this hypothesis is true，why it still shows error when I run "import molgen".
ModuleNotFoundError: No module named 'molgen'
What's more,I saw the molgen is in a file(E:\Python\Lib\site-packages\poetry),named "molgen.so","molgen.pyd",the filename extension-".so" is seem just adjust for Linux systems.
So, whether later versions has supported molgen for windows? If support,what can i do to this error? Thanks!

**Comment by ZhuochenYu** [comment]
Well, that command is for linux so far.
I recommend that you call dataTackle as followings on windows systems:
1. Download pygamd-main.zip, and unzip it to your own windows directory.
2. Open cmd
3. Add the poetry directory to your windows environment variable. Use this command, for example : setx PATH "%PATH%;C:\Users\yzc\Desktop\pygamd-v1-main\pygamd-v1-main\poetry"
or setx /M PATH "%PATH%;\"C:\Users\yzc\Desktop\pygamd-v1-main\pygamd-v1-main\poetry\" then echo %PATH%. Also, you can use GUI to add it.
4. Check whether the path is added to the environment variable. And close cmd.exe.
5. Open Anaconda prompt and activate your pygamd envs.
6.  To use dataTackle: dataTackle.exe xxx.mst

Hope that may help you.



***@***.***
 
From: whereisLan
Date: 2024-09-12 17:07
To: youliangzhu/pygamd-v1
CC: zcyu; Comment
Subject: Re: [youliangzhu/pygamd-v1] import molgen (Issue #4)
Thanks, the problem about molgen have been solved well ! But now,there are a new problem about dataTackle .
Some descript is likely ,"SyntaxError: invalid syntax",
according to the instructions in the manual for running dataTackle,
for example,“The dataTackle can be loaded by the command “from poetry import dataTackle” in Python3. Then you can use dataTackle locally by the command “./dataTackle” ."
So, the question is : Why does my Python program display invalid syntax when I run “./dataTackle”, and what can I do to make it run properly? In other words, what is the correct operation for me to process the data of the MST file that has been run
picture.docx

**Comment by whereisLan** [comment]
Thank! The problem has also been solved. Now I have another problem, that is, I can't find the converted file, which is very distressing. This means that I can't get a visualization, and please teach me how to find this converted file,such as "p.lammps"?
[picture1.docx](https://github.com/user-attachments/files/17041115/picture1.docx)

In addition, I would like to perform a Boltzmann inversion from a coarse-grained model to an all-atomic model on pygamd to verify the accuracy of the force fields in both models，is possible ？Thanks again

**Comment by ZhuochenYu** [comment]
1. In this version, you need to first load .mst to generate .xml file(or directly load .xml file). Then use 19:lammps=true. By the way, OVITO and vmd can directly load .xml file.
2. cu_gala module(see manual.pdf) supports numerical potential, and then you can compare CG and AA model. For example: 10.1021/acs.macromol.3c00315


***@***.***
 
From: whereisLan
Date: 2024-09-18 16:38
To: youliangzhu/pygamd-v1
CC: zcyu; Comment
Subject: Re: [youliangzhu/pygamd-v1] import molgen (Issue #4)
Thank! The problem has also been solved. Now I have another problem, that is, I can't find the converted file, which is very distressing. This means that I can't get a visualization, and please teach me how to find this converted file,such as "p.lammps"?
picture1.docx
In addition, I would like to perform a Boltzmann inversion from a coarse-grained model to an all-atomic model on pygamd to verify the accuracy of the force fields in both models，is possible ？Thanks again

**Comment by whereisLan** [comment]
[Uploading 111.docx…]()
 Recently, I successfully ran DPD by pasting the code directly into the CMD. I am very grateful for your help. Now, I would like to run case-2 (dppc.py) directly by using the command "python xxx.py", but I still get an error - "(pygamd) C:\Users\86185>python A5B5-dpd.py Traceback (most recent call last):
File "C:\Users\86185\A5B5-dpd.py", line 2, in <module>
from poetry import cu_gala as gala
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"ImportError: DLL load failed while importing cu_gala: The specified module could not be found."
     To fix this error, I re-downloaded pygamd using pip and copied the path under poetry to the environment's PATH variable. However, when I ran it again, I still got an error. Do you have any solutions that you can teach me?
     Additionally, there is a common problem that whenever I close my computer and try to open molgen the next day, the system always displays that it cannot find the module. I can only solve this problem by repeatedly using pip to install pygamd. In my memory, it seems that this issue occurred after I followed your advice of "Add the poetry directory to your Windows environment variable. Use this command, for example: setx PATH "%PATH%;C:\Users\yzc\Desktop\pygamd-v1-main\pygamd-v1-main\poetry"". After executing it, it showed a warning: "WARNING: Data being saved is truncated to 1024 characters. ERROR: Access denied to registry path." I'm not sure if these bugs are related.
PS：“conda create -n poetry python=3.11” is still no way.

**Comment by ZhuochenYu** [comment]
> Uploading 111.docx… Recently, I successfully ran DPD by pasting the code directly into the CMD. I am very grateful for your help. Now, I would like to run case-2 (dppc.py) directly by using the command "python xxx.py", but I still get an error - "(pygamd) C:\Users\86185>python A5B5-dpd.py Traceback (most recent call last): File "C:\Users\86185\A5B5-dpd.py", line 2, in from poetry import cu_gala as gala ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ "ImportError: DLL load failed while importing cu_gala: The specified module could not be found." To fix this error, I re-downloaded pygamd using pip and copied the path under poetry to the environment's PATH variable. However, when I ran it again, I still got an error. Do you have any solutions that you can teach me? Additionally, there is a common problem that whenever I close my computer and try to open molgen the next day, the system always displays that it cannot find the module. I can only solve this problem by repeatedly using pip to install pygamd. In my memory, it seems that this issue occurred after I followed your advice of "Add the poetry directory to your Windows environment variable. Use this command, for example: setx PATH "%PATH%;C:\Users\yzc\Desktop\pygamd-v1-main\pygamd-v1-main\poetry"". After executing it, it showed a warning: "WARNING: Data being saved is truncated to 1024 characters. ERROR: Access denied to registry path." I'm not sure if these bugs are related. PS：“conda create -n poetry python=3.11” is still no way.

Those are not problems with PyGAMD. You can remove the poetry PATH from env PATH, and run the absolute path of dataTackle.exe.
To import modules, you can try commands as followings instead of 'from poetry import xxxx'
>>>import pygamd              #step 1
>>>import cu_gala as gala   #step 2
If the above methods still fail, I recommend using pygamd on linux or windows wsl.

**Comment by whereisLan** [comment]
After using wsl,i still found it-"import cu_gala as gala
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory"
Sir，why ‘cu_gala’still importerror？Are this means 'cu_gala'='cuda_galamost'? And i had seen the cu_gala.so  in my pygamd-v1-main file. It is at here already ! why still import bug! sir,please teach me,thanks.

**Comment by ZhuochenYu** [comment]
Check your cuda and python version. PYGAMD can be used on WSL when your environment is configured correctly.



***@***.***
 
From: whereisLan
Date: 2024-10-11 23:57
To: youliangzhu/pygamd-v1
CC: zcyu; Comment
Subject: Re: [youliangzhu/pygamd-v1] import molgen (Issue #4)
After using wsl,i still found it-"import cu_gala as gala
Traceback (most recent call last):
File "", line 1, in 
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory"
Sir，why ‘cu_gala’still importerror？Are this means 'cu_gala'='cuda_galamost'? And i had seen the cu_gala.so in my pygamd-v1-main file. It is at here already ! why still import bug! sir,please teach me,thanks.

**Comment by whereisLan** [comment]
Hello Dr. Yu, excuse me again. The last problem has been solved,
         I am currently working on the construction of CG force fields. Now that the AA-MD work is complete, due to the limitations of scale，I want to use pygamd to convert the force field (AA to CG).
         And I heard that the pygamd software has a very big advantage in this - it can use the setpotential() function program to automatically iteratively invert and obtain the force field, and it only needs to be operated once.
         My first question is: does the current pygamd support this (only once)?
         My second question is: if so, is there any information on the detailed operation of the IBI. I may not understand some of 
the information expressed on the PDF, I hope you can teach me, thank you again, Dr. Yu.

**Comment by ZhuochenYu** [comment]
The cu_gala module supports numerical potential. However, to acheive  IBI workflow, you need to write your own script.
If you need a ready-to-use IBI workflow, try votca + lammps.



***@***.***
 
From: whereisLan
Date: 2024-11-05 18:33
To: youliangzhu/pygamd-v1
CC: zcyu; Comment
Subject: Re: [youliangzhu/pygamd-v1] import molgen (Issue #4)
Hello Dr. Yu, excuse me again. The last problem has been solved,
I am currently working on the construction of CG force fields. Now that the AA-MD work is complete, due to the limitations of scale，I want to use pygamd to convert the force field (AA to CG).
And I heard that the pygamd software has a very big advantage in this - it can use the setpotential() function program to automatically iteratively invert and obtain the force field, and it only needs to be operated once.
My first question is: does the current pygamd support this (only once)?
My second question is: if so, is there any information on the detailed operation of the IBI. I may not understand some of
the information expressed on the PDF, I hope you can teach me, thank you again, Dr. Yu.
