### ISSUE TITLE
当我运行示例是出现问题（No module named 'poetry）

### ISSUE THREAD

**Issue by SHutdog** [youliangzhu/pygamd-v1#5]
当我直接试运行examples里的A5B5.molg时（examples/cuda/Case1-DPD/Phase-Seperation-of-Diblock-Copolymer/systems/A5B5）我遇到了一个报错：
Traceback (most recent call last):
File "/home/yang/桌面/Case1-DPD/Phase-Seperation-of-Diblock-Copolymer/systems/A5B5/A5B5.molg", line 2, in
from poetry import molgen
ModuleNotFoundError: No module named 'poetry'
当我尝试通过“pip install poetry”指令安装poetry后，上述问题并未解决，环境是官方推荐的的环境，这是为什么呢？

**Comment by youliangzhu** [comment]
pip和所用的python保证是一个目录下的



***@***.***
 
发件人： SHutdog
发送时间： 2024-06-21 12:19
收件人： youliangzhu/pygamd-v1
抄送： Subscribed
主题： [youliangzhu/pygamd-v1] 当我运行示例是出现问题（No module named 'poetry） (Issue #5)
当我直接试运行examples里的A5B5.molg时（examples/cuda/Case1-DPD/Phase-Seperation-of-Diblock-Copolymer/systems/A5B5）我遇到了一个报错：
Traceback (most recent call last):
File "/home/yang/桌面/Case1-DPD/Phase-Seperation-of-Diblock-Copolymer/systems/A5B5/A5B5.molg", line 2, in
from poetry import molgen
ModuleNotFoundError: No module named 'poetry'
当我尝试通过“pip install poetry”指令安装poetry后，上述问题并未解决，环境是官方推荐的的环境，这是为什么呢？

**Comment by SHutdog** [comment]
我的pip安装的“poetry在”/home/yang/.local/lib/python3.10/site-packages目录下，我的python在/home/yang/Python-3.11.0下，我该如何修改能够使其工作呢，请赐教

**Comment by youliangzhu** [comment]
路径的问题，应该你所有的pip安装的库都用不了，为啥产生这个问题我不清楚，可以尝试重新安装python，然后用新的python中的pip安装pygamd，保证都是一个用户下



***@***.***
 
发件人： SHutdog
发送时间： 2024-06-21 16:16
收件人： youliangzhu/pygamd-v1
抄送： youliangzhu; Comment
主题： Re: [youliangzhu/pygamd-v1] 当我运行示例是出现问题（No module named 'poetry） (Issue #5)
我的pip安装的“poetry在”/home/yang/.local/lib/python3.10/site-packages目录下，我的python在/home/yang/Python-3.11.0下，我该如何修改能够使其工作呢，请赐教

**Comment by ZhuochenYu** [comment]
1. Download and install Anaconda for windows; Open Anaconda Prompt.
2. Then use 'conda create -n pygamd python=3.11' to build a python env.
3. 'conda activate pygamd' and install cudatoolkit: 'conda install -c 'nvidia/label/cuda-12.2.0' package' 
4. Install pygamd: 'pip install pygamd'

Hope that may help you.  We recommend using conda to manage your environment. Also, we recommend using conda to install cudatoolkit 12.2(conda install -c 'nvidia/label/cuda-12.2.0' package' ).
